network_file: "net/onset_and_pitch_0901.py"
network_class_name: "Split_onset_pitch"
use_strongly_dataset: True
training_dataset_dir: "../MIR-ST500"
training_gt_pkl_label: "MIR-ST500_train_ctcce+30_1027.pkl"
use_weakly_dataset: True
training_weakly_dataset_dir: "../MIR-ST500"
training_weakly_gt_pkl_label: "MIR-ST500_train_weak_1027.pkl"
val_dataset_dir: "../val_set"
val_gt_pkl_label: "MIR-ST500_test_ctcce+30_1027.pkl"
h5py_feature_file_name: "feature.hdf5"
epoch: 100
warmup_epoch: 5
lr: 0.0001
batch_size: 1
model_save_dir: "models"
model_save_prefix: "ctc_ce_test"
log_path: "logger_ctc_ce_test.pkl"